### PR TITLE
Parsing nbest result

### PR DESCRIPTION
**Pull request by teowenshen**
Expanding fugashi.Tagger.nbest to return a List[List[UnidicFeaturesXX]].

### CODE REVIEW

**Comment by teowenshen** [comment]
Apologies. I noticed that this version of my n-best code crashes after several thousand iterations. 

I think that it might be because the mecab_nbest_init function allocated some memory within the tagger for the lattice. If that is the case, so far I am not sure which function destroys that internal lattice. Do you have any experience/advice on that?

On the other hand, my "experiment" with the Lattice class works consistently, but the changes in logic span from the Tagger initialization (creating the lattice, adding request type) to the parse function.

**Comment by polm** [comment]
Thank you for the PR, and sorry it took me a while to get to this. I pushed some fixes.

First, I didn't realize this changed the return type of `nbest`. It's better to return nodes than strings, but since fugashi uses semantic versioning it's not OK to just change return types like that, that would break code of everyone using the existing version. If you have a better idea for the name of the new function I'd be glad to hear it. 

A minor point, but the EOS node shouldn't be wrapped, since it is ignored (I got the commit message wrong, oh well). 

In my tests segfaults seem to be caused by the mecab nbest function returning NULL when there weren't enough paths to support every iteration through the loop. This would happen immediately with an empty string, for example. 

I didn't see anything that suggested the error was related to excessive memory usage. MeCab has some weird internal memory management, but I think the Lattice is re-used. If you have more information that suggests this is a problem let me know.

I think this is OK now, but it needs more testing. If you'd like to add tests similar to the existing ones that would be great, or I can get around to it eventually. Also note that for testing an API thoroughly it's better to use something like a whole book than a long sentence. I tested with the Aozora Bunko edition of Kokoro.

**Comment by teowenshen** [comment]
I used the Japanese dataset for CC-100: Monolingual Datasets from Web Crawl Data and ran at least for 16,777,217 lines.

I didn't use pytest because I couldn't find a way to load the test data lazily. The entire corpus is around 45GB after decompression. 

There were 7 peculiar lines where MeCab couldn't come up with as many tokenised possibilities as requested.  

What do you think about the results?

> 65536 - All lines parsed with enough paths.
> 65536 - All lines recovered
> 131072 - All lines parsed with enough paths.
> 131072 - All lines recovered
> 262144 - All lines parsed with enough paths.
> 262144 - All lines recovered
> 524288 - All lines parsed with enough paths.
> 524288 - All lines recovered
> 1048576 - Not enough paths (counts = 1): 806683
> 1048576 - All lines recovered
> 2097152 - Not enough paths (counts = 1): 806683
> 2097152 - All lines recovered
> 4194304 - Not enough paths (counts = 3): 806683, 4096098, 4096099
> 4194304 - All lines recovered
> 8388608 - Not enough paths (counts = 7): 806683, 4096098, 4096099, 6534587, 7627155, 7627159, 7627161
> 8388608 - All lines recovered
> 16777217 - Not enough paths (counts = 7): 806683, 4096098, 4096099, 6534587, 7627155, 7627159, 7627161
> 16777217 - All lines recovered
> 
> The contents of the lines are as below:-
> 806683: '････････････｜･･････････････････｜･･･････････････････････････････････････････････････････････････｜･･･････････････｜････････････････････････2149･･･22192249'
> 4096098: '│││リ││││'
> 4096099: '││││ル│││'
> 6534587: '稼働率13138211181822'
> 7627155: '75も426274'
> 7627159: '59だ123590'
> 7627161: '99場合112120'

**Comment by polm** [comment]
Sorry it took me a while to follow up, but thanks for the extensive test! It's great to have a really thorough test like that. I modified it so it won't run in CI (don't need it run on every commit) but it'll be good reference.

Not getting enough paths through those strings is no problem, with the version of UniDic I distribute numbers have to be one token, so there's only so many variations. 

I made a few more modifications:

- I added short tests, like the existing ones, to run on regular commits and keep from introducing errors
- I renamed the function to `nbestToNodeList`, to better fit with the `parse` and `parseToNodeList` pattern

Thanks again for all your work on this, this is a great feature to have! I'll make a release with this in the near future.

**Pull request merged**
